anrm='adb shell pm uninstall -k --user 0'
#samsung
$anrm com.dsi.ant.sample.acquirechannels
$anrm com.dsi.ant.service.socket
$anrm com.dsi.ant.server
$anrm com.dsi.ant.plugins.antplus
$anrm flipboard.boxer.app
$anrm com.cnn.mobile.android.phone.edgepanel
$anrm com.sec.android.easyonehand
$anrm com.samsung.android.widgetapp.yahooedge.finance
$anrm com.android.dreams.phototable
$anrm com.google.android.printservice.recommendation
$anrm com.android.printspooler
$anrm com.samsung.android.widgetapp.yahooedge.sport
$anrm com.samsung.android.spdfnote
$anrm com.sec.android.daemonapp
$anrm com.samsung.android.weather
$anrm com.samsung.android.app.reminder
$anrm com.hancom.office.editor.hidden
$anrm com.samsung.android.keyguardwallpaperupdator
$anrm com.samsung.android.app.news
$anrm com.android.egg
$anrm com.sec.android.widgetapp.samsungapps
# samsung store
$anrm com.samsung.android.themestore
$anrm com.sec.android.app.samsungapps
# SAMSUNG GAME LAUNCHER
$anrm com.samsung.android.game.gamehome
$anrm com.enhance.gameservice
$anrm com.samsung.android.game.gametools
# SAMSUNG BROWSER
$anrm com.sec.android.app.sbrowser
$anrm com.samsung.android.app.sbrowseredge
# SAMSUNG EMAIL
$anrm com.samsung.android.email.provider
$anrm com.wsomacp
# FACEBOOK
$anrm com.facebook.katana
$anrm com.facebook.system
$anrm com.facebook.appmanager
$anrm com.facebook.services
# VR
$anrm com.samsung.android.hmt.vrsvc
$anrm com.samsung.android.app.vrsetupwizardstub
$anrm com.samsung.android.hmt.vrshell
# SAMSUNG LED COVER
$anrm com.samsung.android.app.ledcoverdream
$anrm com.sec.android.cover.ledcover
$anrm com.sec.android.app.desktoplauncher
$anrm com.sec.android.app.withtv
# GOOGLE
$anrm com.google.android.googlequicksearchbox
$anrm com.google.android.apps.tachyon
$anrm com.google.android.music
$anrm com.google.android.apps.docs
$anrm com.google.android.apps.maps
$anrm com.google.android.apps.photos
$anrm com.google.android.youtube
$anrm com.google.android.videos
$anrm com.google.android.apps.books
$anrm com.google.android.apps.magazines
$anrm com.google.android.apps.plus
# microsok
$anrm com.microsoft.skydrive
$anrm com.skype.raider
$anrm com.microsoft.office.excel
$anrm com.microsoft.office.word
$anrm com.microsoft.office.powerpoint
# samsung optional
$anrm com.sec.android.easyMover
$anrm com.sec.android.easyMoverAgent
$anrm com.samsung.android.smartcallprovider
$anrm com.samsung.android.easysetup
$anrm com.samsung.android.ststub
$anrm com.samsung.android.beaconmanager
$anrm com.samsung.systemui.bixby2
$anrm com.samsung.android.visionintelligence
$anrm com.samsung.android.app.spage
$anrm com.samsung.android.app.settings.bixby
$anrm com.samsung.android.bixby.service
$anrm com.samsung.android.bixby.agent
$anrm com.samsung.android.bixby.agent.dummy
$anrm com.samsung.android.bixby.es.globalaction
$anrm com.samsung.android.bixby.plmsyn
$anrm com.samsung.android.bixby.voiceinput
$anrm com.samsung.android.bixby.wakeup
$anrm com.samsung.android.hmt.vrsvc
$anrm com.samsung.android.app.vrsetupwizardstub
$anrm com.samsung.android.hmt.vrshell
$anrm com.google.vr.vrcore
# to install google versionnnnn
$anrm com.sec.android.app.launcher #### INSTALL ANOTHER STABLE LAUNCHER FIRST!!!!!
$anrm com.samsung.android.calendar  ### INSTALL GOOGLE CALENDAR 
$anrm com.sec.android.messaging #### INSTALL GOOGLE MESSAGING APPP
$anrm com.samsung.android.messaging #### INSTALL GOOGLE MESSAGING APPP
$anrm com.google.android.apps.maps ### INSTALL GOOGLE MAPS LITE
###  under test
$anrm com.samsung.android.mobileservice
$anrm com.sec.android.easyMover.Agent
$anrm com.samsung.android.smartswitchassistant
$anrm com.samsung.android.mateagent
$anrm com.samsung.desktopsystemui
$anrm com.samsung.android.app.aodservice
$anrm com.samsung.android.service.peoplestripe
$anrm com.samsung.android.app.cocktailbarservice
$anrm com.samsung.android.rubin.app
$anrm com.samsung.android.fmm # if using google for WHERE IS MY PHONE
$anrm com.sec.epdg
$anrm com.sec.epdgtestapp
$anrm com.sec.enterprise.knox.attestation
$anrm com.sec.enterprise.knox.cloudmdm.smdms
$anrm com.samsung.android.knox.containeragent
$anrm com.samsung.android.knox.containercore
$anrm com.samsung.knox.securefolder
$anrm com.android.managedprovisioning
$anrm com.sec.android.diagmonagent
$anrm com.samsung.android.app.appsedge
$anrm com.samsung.android.app.talkback
$anrm com.samsung.android.samsungpassautofill
$anrm com.knox.vpn.proxyhandler
$anrm com.sec.android.desktopcommunity
$anrm com.android.wallpaper.livepicker
$anrm com.samsung.daydream.customization
$anrm com.sec.android.app.safetyassurance
$anrm com.samsung.safetyinformation
$anrm com.sec.android.widgetapp.webmanual
$anrm com.sec.android.desktopmode.uiservice
$anrm com.sec.android.app.apex
$anrm com.samsung.android.sm.devicesecurity
$anrm com.samsung.android.drivelink.stub
$anrm com.samsung.android.universalswitch
$anrm com.samsung.android.kidsinstaller
$anrm com.android.hotwordenrollment.xgoogle
$anrm com.android.hotwordenrollment.xgoogle
$anrm com.samsung.SMT
$anrm com.samsung.android.svcagent
$anrm com.sec.vsim.ericssonnsds.webapp
$anrm com.samsung.systemui.hidenotch
$anrm com.sec.automation
$anrm com.samsung.android.bbc.bbcagent
$anrm com.samsung.android.app.watchmanagerstub
$anrm com.samsung.android.scloud
$anrm com.samsung.android.samsungpass
$anrm com.samsung.android.wallpaper.res
$anrm com.sec.enterprise.mdm.services.simpin
$anrm com.samsung.android.mdm
$anrm com.samsung.android.location
$anrm com.google.android.partnersetup
$anrm com.android.providers.partnerbookmarks
$anrm com.sec.android.app.personalization
$anrm com.sec.spp.push
$anrm com.android.pacprocessor
$anrm com.android.dreams.basic
$anrm com.android.apps.tag
$anrm com.android.wallpaperbackup
$anrm com.android.providers.userdictionary
$anrm com.android.captiveportallogin
$anrm com.sec.android.app.billing
$anrm com.samsung.klmsagent
$anrm com.sec.android.uibcvirtualsoftkey
$anrm com.sem.factoryapp
$anrm com.sec.android.app.factorykeystring
$anrm com.sec.android.service.health
$anrm com.sec.ims
$anrm com.sec.imsservice
$anrm com.sec.imslogger
$anrm com.samsung.advp.imssettings
$anrm com.samsung.android.sm.policy
$anrm com.samsung.android.knox.analytics.uploader
$anrm com.sec.android.app.DataCreate
$anrm com.samsung.android.allshare.service.mediashare
$anrm com.sec.android.app.quicktool
$anrm com.samsung.android.dqagent
$anrm com.sec.android.app.ringtoneBR
$anrm com.monotype.android.font.chococooky
$anrm com.samsung.android.authfw
$anrm com.google.android.feedback
$anrm com.samsung.android.allshare.service.fileshare
$anrm com.google.android.backuptransport
$anrm com.google.android.onetimeinitializer
$anrm com.samsung.clipboardsaveservice
$anrm com.samsung.svoice.sync
$anrm com.sec.android.app.parser
$anrm com.sec.location.nsflp2
$anrm com.samsung.android.smartmirroring
$anrm com.monotype.android.font.rosemary
#uninstalling this killls the samsung camera com.samsung.android.provider.filterprovider 
$anrm com.gd.mobicore.pa
$anrm com.samsung.android.app.galaxyfinder
$anrm com.skms.android.agent
$anrm com.sec.usbsettings
$anrm com.sec.android.easyMover.Agent
$anrm com.sec.android.widgetapp.easymodecontactswidget
$anrm com.sec.android.app.wlantest
$anrm com.sec.sve
$anrm com.sec.android.AutoPreconfig
$anrm com.sec.android.app.soundalive
$anrm com.sec.android.providers.security
$anrm com.samsung.android.securitylogagent
$anrm com.samsung.android.app.assistantmenu
$anrm com.sec.android.app.SecSetupWizard
$anrm com.sec.android.app.hwmoduletest
$anrm com.sec.bcservice
$anrm com.sec.modem.settings
$anrm com.samsung.android.providers.context
$anrm com.sec.android.app.servicemodeapp
$anrm com.sec.android.preloadinstaller
$anrm com.sec.android.preloadinstaller
$anrm com.samsung.storyservice
$anrm com.samsung.android.app.simplesharing
$anrm com.samsung.android.app.taskedge
$anrm com.samsung.android.app.advsounddetector
$anrm com.sec.android.RilServiceModeApp
$anrm com.samsung.android.app.mirrorlink
$anrm com.samsung.crane
$anrm com.samsung.android.clipboarduiservice
$anrm com.sec.mldapchecker
$anrm com.samsung.android.spayfw
$anrm com.sec.android.app.bluetoothtest
$anrm com.sec.hearingadjust
$anrm com.sec.android.splitsound
$anrm com.samsung.android.networkdiagnostic
$anrm com.samsung.android.app.omcagent
$anrm com.monotype.android.font.cooljazz
$anrm com.samsung.android.sdk.handwriting
$anrm com.samsung.aasaservice
$anrm com.sec.android.app.applinker
$anrm com.samsung.android.app.clipboardedge
$anrm com.samsung.ipservice
$anrm com.samsung.sec.android.application.csc
